name: chat_app
description: App chat

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.7.1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  firebase_crashlytics: ^3.1.0
  firebase_messaging: ^14.6.1
  #  firebase_in_app_messaging: ^0.7.3+1

  fluttertoast: ^8.1.2
  url_launcher: ^6.1.10

  font_awesome_flutter: ^9.0.0

  #Flutter library to load and cache network images. Can also be used with placeholder and error widgets.
  cached_network_image: ^3.2.3

  shared_preferences: ^2.1.1

  google_fonts: ^4.0.4

  # A string-based path manipulation library.
  path: ^1.8.2

  #Flutter plugin for getting commonly used locations on host platform file systems, such as the temp and app data directories.
  path_provider: ^2.0.15

  #Flutter plugin for selecting images from the Android and iOS image library, and taking new pictures with the camera.
  image_picker: ^0.8.7+5

  # Flutter library to keep the device screen awake
  wakelock: ^0.6.2

  #Photo View provides a gesture sensitive zoomable widget. Photo View is largely used to show interactive images and other stuff such as SVG.
  photo_view: ^0.14.0

  #A Flutter package than allow expand and collapse text dynamically
  readmore: ^2.2.0

  #Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android.
  flutter_secure_storage: ^8.0.0

  #A cross platform plugin for displaying and scheduling local notifications for Flutter applications with the ability to customise for each platform.
  flutter_local_notifications: ^13.0.0

  #Flutter plugin for discovering the state of the network (WiFi & mobile/cellular) connectivity on Android and iOS.
  connectivity_plus: ^3.0.6

  #A powerful HTTP package for Dart/Flutter, which supports Global settings, Interceptors, FormData, Aborting and canceling a request, Files uploading and downloading, Requests timeout, Custom adapters, etc.
  dio: ^5.1.2

  #A package for creating badges. Badges can be used for an additional marker for any widget, e.g. show a number of items in a shopping cart.
  badges: ^3.1.1

  #Plugin to update the app badge on the launcher (both for Android, iOS and macOS)
  flutter_app_badger: ^1.5.0

  #Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
  flutter_bloc: ^8.1.3

  #A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.5

  #Customizable animated page indicator with a set of built-in effects.
  smooth_page_indicator: ^1.1.0

  #A custom switch widget that can have a custom height and width, borders, border radius, colors, toggle size, custom text and icons inside the toggle.
  flutter_switch: ^0.3.2

  #Fully customizable OTP Entry TextField for flutter, Widget accepts pin of any length. Its written in pure dart, no extra dependency.
  flutter_otp_text_field: ^1.1.1

  flutter_plugin_android_lifecycle: ^2.0.15

  flutter_datetime_picker_plus: ^2.1.0

  zego_uikit_prebuilt_call: ^3.3.10

  just_audio: ^0.9.33

  #A Flutter package that provides an Emoji picker widget with 1500+ emojis in 8 categories.
  emoji_picker_flutter: ^1.5.4

  flutter_gen: ^5.4.0

  permission_handler: ^10.2.0



  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  flutter_launcher_icons: ^0.12.0
  flutter_gen_runner:
  build_runner:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 26

flutter_gen:
  output: lib/l10n/ # Optional (default: lib/gen/)
  line_length: 300 # Optional (default: 80)

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/sound/
