name: chat_app
description: App chat

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.3.8"

dependencies:
  cloud_firestore: ^4.2.0
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  shared_preferences: ^2.0.15
  #firebase_core_platform_interface: 4.5.1

  google_fonts: ^3.0.1

  #Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android.
  flutter_secure_storage: ^8.0.0

  #iOS implementation of the local_auth plugin.
  local_auth_ios: ^1.0.13

  #Android implementation of the local_auth plugin.
  local_auth_android: ^1.0.19

  #Flutter plugin for Android and iOS devices to allow local authentication via fingerprint, touch ID, face ID, passcode, pin, or pattern.
  local_auth: ^2.1.5

  #A cross platform plugin for displaying and scheduling local notifications for Flutter applications with the ability to customise for each platform.
  flutter_local_notifications: ^13.0.0

  #Flutter plugin for discovering the state of the network (WiFi & mobile/cellular) connectivity on Android and iOS.
  connectivity_plus: ^3.0.3

  #A powerful HTTP package for Dart/Flutter, which supports Global settings, Interceptors, FormData, Aborting and canceling a request, Files uploading and downloading, Requests timeout, Custom adapters, etc.
  dio: ^5.0.1

  #A cookie manager for Dio, which supports persistent cookies in RAM and file.
  dio_cookie_manager: ^2.1.1

  #This small library helps you to decode Json Web Tokens, you can also know if a JWT is a
  jwt_decoder: ^2.0.1

  #A package for creating badges. Badges can be used for an additional marker for any widget, e.g. show a number of items in a shopping cart.
  badges: ^3.0.2

  #Plugin to update the app badge on the launcher (both for Android, iOS and macOS)
  flutter_app_badger: ^1.5.0

  #Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
  flutter_bloc: ^8.1.2

  #A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.5

  #the framework will help localize Flutter application without the headache
  l10n_flutter: ^1.0.6

  #Customizable animated page indicator with a set of built-in effects.
  smooth_page_indicator: ^1.0.1

  #A package that simplifies the access most of used properties/fuctions right in the BuildContext.
  #build_context: ^3.0.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    #- i18n/
