name: chat_app
description: App chat

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.3.8"

dependencies:
  cloud_firestore: ^4.4.0
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.11
  firebase_messaging: ^14.2.3
  firebase_in_app_messaging: ^0.7.0+11

  #Flutter library to load and cache network images. Can also be used with placeholder and error widgets.
  cached_network_image: ^3.2.3

  shared_preferences: ^2.0.15

  google_fonts: ^3.0.1

  # A string-based path manipulation library.
  path: ^1.6.4

  #Flutter plugin for getting commonly used locations on host platform file systems, such as the temp and app data directories.
  path_provider: ^2.0.12

  #Flutter plugin for selecting images from the Android and iOS image library, and taking new pictures with the camera.
  image_picker: ^0.8.6
  video_thumbnail: ^0.5.3
  cached_video_player: ^2.0.3

  permission_handler: ^10.2.0

  # Flutter library to keep the device screen awake
  wakelock: ^0.6.2

  #Photo View provides a gesture sensitive zoomable widget. Photo View is largely used to show interactive images and other stuff such as SVG.
  photo_view: ^0.14.0

  #A Flutter package than allow expand and collapse text dynamically
  readmore: ^2.0.0

  #Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: ^0.17.0

  #Flutter Secure Storage provides API to store data in secure storage. Keychain is used in iOS, KeyStore based solution is used in Android.
  flutter_secure_storage: ^8.0.0

  #iOS implementation of the local_auth plugin.
  local_auth_ios: ^1.0.13

  #Android implementation of the local_auth plugin.
  local_auth_android: ^1.0.19

  #Flutter plugin for Android and iOS devices to allow local authentication via fingerprint, touch ID, face ID, passcode, pin, or pattern.
  local_auth: ^2.1.5

  #A cross platform plugin for displaying and scheduling local notifications for Flutter applications with the ability to customise for each platform.
  flutter_local_notifications: ^13.0.0

  #Flutter plugin for discovering the state of the network (WiFi & mobile/cellular) connectivity on Android and iOS.
  connectivity_plus: ^3.0.3

  #A powerful HTTP package for Dart/Flutter, which supports Global settings, Interceptors, FormData, Aborting and canceling a request, Files uploading and downloading, Requests timeout, Custom adapters, etc.
  dio: ^5.0.1

  #A cookie manager for Dio, which supports persistent cookies in RAM and file.
  dio_cookie_manager: ^2.1.1

  #A package for creating badges. Badges can be used for an additional marker for any widget, e.g. show a number of items in a shopping cart.
  badges: ^3.0.2

  #Plugin to update the app badge on the launcher (both for Android, iOS and macOS)
  flutter_app_badger: ^1.5.0

  #Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.
  flutter_bloc: ^8.1.2

  #A Dart package that helps to implement value based equality without needing to explicitly override == and hashCode.
  equatable: ^2.0.5

  #the framework will help localize Flutter application without the headache
  #l10n_flutter: ^1.0.6

  #Customizable animated page indicator with a set of built-in effects.
  smooth_page_indicator: ^1.0.1

  #A custom switch widget that can have a custom height and width, borders, border radius, colors, toggle size, custom text and icons inside the toggle.
  flutter_switch: ^0.3.2

  #Fully customizable OTP Entry TextField for flutter, Widget accepts pin of any length. Its written in pure dart, no extra dependency.
  flutter_otp_text_field: ^1.1.1

  flutter_plugin_android_lifecycle: ^2.0.8

  flutter_datetime_picker: ^1.5.1

  #A Flutter package that provides an Emoji picker widget with 1500+ emojis in 8 categories.
  emoji_picker_flutter: ^1.5.4

  overlay_support:

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 26

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    #- i18n/
